### ISSUE TITLE
fix this for C 4.8/9

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_geodistance#11]
https://github.com/MetaModels/attribute_geodistance/blob/master/src/Attribute/GeoDistance.php#L102

**Comment by discordier** [comment]
Addendum: the referenced service is private/non public.

In Contao 4.4 this is a deprecation, in Contao 4.8+ (due to Symfony 4.x being used) this is a fatal error.

The question is now, do we need to make the service public or do we have to introduce an own service into this package?

**Comment by discordier** [comment]
After discussion with @baumannsven, we want to keep the service private and rather use the way via framework for the fallback in the constructor.

**Comment by discordier** [comment]
Fixed in #13
