### ISSUE TITLE
Keine Ausgabe der Entfernung

### ISSUE THREAD

**Issue by bastlwastl** [MetaModels/attribute_geodistance#2]
Contao 3.5.9
metamodels/bundle_all 2.0.0
metamodels/filter_perimetersearch   2.0.0-alpha2
metamodels/attribute_geodistance    2.0.0-alpha3

**attribute_geodistance Einstellungen:**
Attribut-Typ: Geo Distance
Spaltenname: distance
Name: Geo Distance
Beschreibung: -
Varianten überschreiben: -
Eindeutige Werte: -
GET-Parameter for Geo: geo_lat
GET-Parameter for country: -
Datamode: Multi Mode - Two attributes
Attribute - Latitude: Latitude [text]
Attribute - Longitude: Longitute [text]
LookUp Services: google_maps 

Es wird lediglich ein `-1` ausgegeben.

**Comment by bastlwastl** [comment]
**Getestet mit attribute_geodistance 2.0.0-alpha4** 
Gleiches Ergebniss - es wird lediglich ein `-1` ausgegeben.

**Comment by bastlwastl** [comment]
Die Ausgabe der Entfernung funktioniert erst, wenn bei der Sortierung der Liste **Geo Distance** ausgewählt wurde.

**Comment by discordier** [comment]
@zonky2 might be worth to write this in the documentation of the attribute_geodistance.

**Comment by zonky2** [comment]
@stefanheimes have a new readme text...

**Comment by discordier** [comment]
@zonky2 ehrm... something like this needs to be documented along with the attribute at all.
