### ISSUE TITLE
Vorgabe für den Ländermodus wie bei Perimeter search filter

### ISSUE THREAD

**Issue by bastlwastl** [MetaModels/attribute_geodistance#3]
Vorgabe für den Ländermodus wie bei **Perimeter search filter** ob und wenn ja welches Land der Adresse für die Lookup-Suche hinzugefügt werden soll mit folgenden Optionen:
- Nichts
- Voreinstellung aus Systemeinstellungen
- GET-Parameter verwenden

**Comment by zonky2** [comment]
soll das ein Posting für ein Feature Request sein..?

**Comment by bastlwastl** [comment]
Ja, ich denke schon.

**Comment by zonky2** [comment]
Implementiert

![FireShot Pro Webpage Screenshot #210 - 'MetaModels I www_amoe_de' - www_amoe_de](https://user-images.githubusercontent.com/1045318/104946974-3b163680-59bb-11eb-84fc-94258ad578b1.jpg)
